-- Menu Sushi Smile (carte réelle, juin 2026). Idempotent.
-- À exécuter APRÈS schema.sql. Régénéré par scripts (ne pas éditer à la main).

insert into categories (name, slug, display_order) values
  ('Sushis', 'sushis', 1),
  ('Makis', 'makis', 2),
  ('California', 'california', 3),
  ('Maki Light', 'maki-light', 4),
  ('Snow Roll', 'snow-roll', 5),
  ('Crispy', 'crispy', 6),
  ('Salmon', 'salmon', 7),
  ('Egg Roll', 'egg-roll', 8),
  ('Spécialités', 'specialites', 9),
  ('Chirashis', 'chirashis', 10),
  ('Sashimis', 'sashimis', 11),
  ('Tatakis', 'tatakis', 12),
  ('Tartares', 'tartares', 13),
  ('Pokebowls', 'pokebowls', 14),
  ('Temaki Wrap', 'temaki', 15),
  ('Yakitoris', 'yakitoris', 16),
  ('Nouilles japonaises', 'nouilles', 17),
  ('Entrées & accompagnements', 'entrees', 18),
  ('Nos Menus', 'menus', 19),
  ('Menus à partager', 'menus-partager', 20),
  ('Desserts', 'desserts', 21),
  ('Boissons', 'boissons', 22)
on conflict (slug) do nothing;

insert into products (category_id, name, description, price, is_available, display_order)
select c.id, v.name, v.description, v.price, v.is_available, v.display_order
from (values
  ('sushis','Sushi Thon','2 pièces · thon',5.30,true,1),
  ('sushis','Sushi Crevettes','2 pièces · crevettes',5.30,true,2),
  ('sushis','Sushi Saumon Avocat','2 pièces · saumon, avocat',5.40,true,3),
  ('sushis','Sushi Saumon Cheese','2 pièces · saumon, cheese',5.30,true,4),
  ('sushis','Sushi Saumon','2 pièces · saumon',4.80,true,5),
  ('sushis','Sushi Saumon Tataki','2 pièces · saumon tataki',5.30,true,6),
  ('makis','Maki Saumon','8 pièces · saumon',5.20,true,7),
  ('makis','Maki Saumon Avocat','8 pièces · saumon, avocat',5.70,true,8),
  ('makis','Maki Thon','8 pièces · thon',5.70,true,9),
  ('makis','Maki Crevettes','8 pièces · crevettes',5.70,true,10),
  ('makis','Maki Thon Cuit Mayo','8 pièces · thon cuit, mayo',5.50,true,11),
  ('makis','Maki Concombre','8 pièces · concombre',4.80,true,12),
  ('makis','Maki Avocat Sésame','8 pièces · avocat, sésame',5.00,true,13),
  ('makis','Maki Cheese','8 pièces · cheese',4.90,true,14),
  ('makis','Maki Chèvre Frais Miel','8 pièces · chèvre frais, miel',5.40,true,15),
  ('makis','Maki Thon Avocat','8 pièces · thon, avocat',5.80,true,16),
  ('makis','Maki Crevettes Avocat','8 pièces · crevettes, avocat',5.70,true,17),
  ('makis','Maki Avocat Cheese','8 pièces · avocat, cheese',5.30,true,18),
  ('makis','Maki Crevettes Mayo','8 pièces · crevettes, mayo',5.70,true,19),
  ('california','California Surimi Avocat Mayo','8 pièces · surimi, avocat, mayo',6.20,true,20),
  ('california','California Saumon Avocat','8 pièces · saumon, avocat',6.20,true,21),
  ('california','California Saumon Cheese','8 pièces · saumon, cheese',6.20,true,22),
  ('california','California Thon Avocat','8 pièces · thon, avocat',6.40,true,23),
  ('california','California Thon Cuit Avocat Mayo','8 pièces · thon cuit, avocat, mayo',6.00,true,24),
  ('california','California Crevettes Avocat Mayo','8 pièces · crevettes, avocat, mayo',6.20,true,25),
  ('california','California Avocat Boursin Saumon','8 pièces · avocat, boursin, saumon',6.70,true,26),
  ('california','California Poulet Avocat Spicy','8 pièces · poulet, avocat, spicy',7.10,true,27),
  ('california','California Crevette Tempura Avocat Spicy','8 pièces · crevette tempura, avocat, spicy',7.10,true,28),
  ('california','California Poulet Mayo Crevettes','8 pièces · poulet, mayo, crevettes',7.70,true,29),
  ('maki-light','Maki Light Avocat Cheese Menthe Concombre','8 pièces · avocat, cheese, menthe, concombre',6.40,true,30),
  ('maki-light','Maki Light Thon Avocat','8 pièces · thon, avocat',6.60,true,31),
  ('maki-light','Maki Light Thon Cuit Avocat Mayo','8 pièces · thon cuit, avocat, mayo',6.60,true,32),
  ('maki-light','Maki Light Avocat Boursin Concombre','8 pièces · avocat, boursin, concombre',6.40,true,33),
  ('maki-light','Maki Light Chèvre Miel Tomate Séchée','8 pièces · chèvre, miel, tomate séchée',6.60,true,34),
  ('maki-light','Maki Light Crevettes Tempura Avocat Spicy','8 pièces · crevettes tempura, avocat, spicy',7.40,true,35),
  ('maki-light','Maki Light Crevettes Avocat Mayo','8 pièces · crevettes, avocat, mayo',6.80,true,36),
  ('maki-light','Maki Light Saumon Avocat Menthe','8 pièces · saumon, avocat, menthe',6.70,true,37),
  ('maki-light','Maki Light Poulet Pané Avocat Mayo','8 pièces · poulet pané, avocat, mayo',7.40,true,38),
  ('snow-roll','Snow Roll Saumon','8 pièces · saumon',5.20,true,39),
  ('snow-roll','Snow Roll Saumon Avocat','8 pièces · saumon, avocat',5.70,true,40),
  ('snow-roll','Snow Roll Saumon Cheese','8 pièces · saumon, cheese',5.70,true,41),
  ('snow-roll','Snow Roll Avocat Sésame','8 pièces · avocat, sésame',4.90,true,42),
  ('snow-roll','Snow Roll Thon','8 pièces · thon',5.50,true,43),
  ('snow-roll','Snow Roll Thon Cuit','8 pièces · thon cuit',5.10,true,44),
  ('snow-roll','Snow Roll Thon Cuit Cheese','8 pièces · thon cuit, cheese',5.20,true,45),
  ('snow-roll','Snow Roll Thon Cuit Avocat','8 pièces · thon cuit, avocat',5.20,true,46),
  ('snow-roll','Snow Roll Crevettes Mayo','8 pièces · crevettes, mayo',5.40,true,47),
  ('snow-roll','Snow Roll Crevettes Tempura Avocat Spicy','8 pièces · crevettes tempura, avocat, spicy',6.80,true,48),
  ('snow-roll','Snow Roll Poulet Pané Boursin','8 pièces · poulet pané, boursin',7.00,true,49),
  ('snow-roll','Snow Roll Poulet Mayo Crevettes','8 pièces · poulet, mayo, crevettes',7.00,true,50),
  ('crispy','Crispy Saumon Avocat Boursin','8 pièces · saumon, avocat, boursin',7.40,true,51),
  ('crispy','Crispy Poulet Pané Cheese','8 pièces · poulet pané, cheese',7.80,true,52),
  ('crispy','Crispy Thon Cuit Avocat Mayo','8 pièces · thon cuit, avocat, mayo',7.00,true,53),
  ('crispy','Crispy Concombre Avocat Cheese','8 pièces · concombre, avocat, cheese',7.00,true,54),
  ('crispy','Crispy Chèvre Frais Tomate Séchée Miel','8 pièces · chèvre frais, tomate séchée, miel',7.40,true,55),
  ('crispy','Crispy Thon Avocat Cheese','8 pièces · thon, avocat, cheese',7.60,true,56),
  ('crispy','Crispy Saumon Cuit Panko Miel Gingembre','8 pièces · saumon cuit, panko, miel, gingembre',7.60,true,57),
  ('crispy','Crispy Poulet Mayo Crevette','8 pièces · poulet, mayo, crevette',7.80,true,58),
  ('salmon','Salmon Cheese','6 pièces · cheese',6.80,true,59),
  ('salmon','Salmon Boursin','6 pièces · boursin',6.80,true,60),
  ('salmon','Salmon Avocat Cheese','6 pièces · avocat, cheese',7.00,true,61),
  ('salmon','Salmon Concombre Cheese','6 pièces · concombre, cheese',6.50,true,62),
  ('salmon','Salmon Chèvre Frais Tomate Séchée Miel','6 pièces · chèvre frais, tomate séchée, miel',7.00,true,63),
  ('salmon','Salmon Avocat','6 pièces · avocat',6.80,true,64),
  ('egg-roll','Egg Roll Cheese','8 pièces · cheese',5.40,true,65),
  ('egg-roll','Egg Roll Saumon Avocat','8 pièces · saumon, avocat',5.90,true,66),
  ('egg-roll','Egg Roll Saumon Cheese','8 pièces · saumon, cheese',5.90,true,67),
  ('egg-roll','Egg Roll Thon Cuit Avocat','8 pièces · thon cuit, avocat',5.60,true,68),
  ('specialites','Dragon','8 pièces · california, poulet pané, poivrons, sauce spicy, top avocat, crispy',9.00,true,69),
  ('specialites','Le Spécial','8 pièces · california, crevettes tempura, concombre, sauce spicy, top avocat / saumon braisé',9.00,true,70),
  ('specialites','Sushi Burrito','Maki XL · saumon tataki, salade, carotte, concombre, avocat, sauce sriracha',10.90,true,71),
  ('specialites','Rainbow','8 pièces · california saumon/avocat/thon/saumon/crevette',10.80,true,72),
  ('specialites','Gold Saumon','8 pièces · california panko, saumon, avocat',10.90,true,73),
  ('specialites','Gold Crevettes Tempura','8 pièces · california panko, crevettes tempura, avocat',10.90,true,74),
  ('specialites','Gold Thon Cuit','8 pièces · california panko, thon cuit, avocat',10.90,true,75),
  ('specialites','Gold Chèvre Miel','8 pièces · snow roll panko, chèvre, miel',10.90,true,76),
  ('chirashis','Chirashi Saumon','saumon sur riz vinaigré',17.20,true,77),
  ('chirashis','Chirashi Thon','thon sur riz vinaigré',18.50,true,78),
  ('chirashis','Chirashi Mixte','saumon, thon',18.50,true,79),
  ('chirashis','Chirashi Saumon Tataki Cheese','saumon tataki, cheese',19.20,true,80),
  ('chirashis','Chirashi Thon Tataki Cheese','thon tataki, cheese',19.20,true,81),
  ('sashimis','Sashimi Saumon x6','6 tranches de saumon',6.90,true,82),
  ('sashimis','Sashimi Thon x6','6 tranches de thon',7.30,true,83),
  ('sashimis','Sashimi Saumon Thon x6','6 tranches · saumon, thon',7.90,true,84),
  ('sashimis','Sashimi Saumon x12','12 tranches de saumon',12.50,true,85),
  ('sashimis','Sashimi Thon x12','12 tranches de thon',13.50,true,86),
  ('sashimis','Sashimi Saumon Thon x12','12 tranches · saumon, thon',13.90,true,87),
  ('tatakis','Tataki Saumon x6','6 pièces · saumon',7.90,true,88),
  ('tatakis','Tataki Saumon x12','12 pièces · saumon',13.90,true,89),
  ('tatakis','Tataki Thon x6','6 pièces · thon',8.30,true,90),
  ('tatakis','Tataki Thon x12','12 pièces · thon',14.50,true,91),
  ('tartares','Tartare Saumon Avocat','saumon, avocat',12.90,true,92),
  ('tartares','Tartare Thon Avocat','thon, avocat',14.90,true,93),
  ('tartares','Tartare Thon Cuit Avocat','thon cuit, avocat',11.90,true,94),
  ('tartares','Tartare Duo Saumon Thon','saumon & thon, poivrons, oignons, sauce yuzu, coriandre',15.90,true,95),
  ('pokebowls','Pokebowl Saumon','saumon, riz, légumes',15.80,true,96),
  ('pokebowls','Pokebowl Saumon Tataki','saumon tataki, riz, légumes',15.80,true,97),
  ('pokebowls','Pokebowl Thon','thon, riz, légumes',16.80,true,98),
  ('pokebowls','Pokebowl Thon Tataki','thon tataki, riz, légumes',16.80,true,99),
  ('pokebowls','Pokebowl Crevettes','crevettes, riz, légumes',16.80,true,100),
  ('pokebowls','Pokebowl Poulet Pané','poulet pané, riz, légumes',15.50,true,101),
  ('pokebowls','Pokebowl Végétarien','légumes, riz',13.00,true,102),
  ('pokebowls','Pokebowl Crevettes Tempura','crevettes tempura, riz, légumes',16.80,true,103),
  ('temaki','Temaki Poulet Pané','poulet pané, avocat, salade, spicy',6.80,true,104),
  ('temaki','Temaki Chèvre Frais','chèvre frais, cheese, tomates séchées, miel, salade',6.80,true,105),
  ('temaki','Temaki Saumon','saumon, avocat, cheese, salade',7.40,true,106),
  ('temaki','Temaki Crevette Tempura','crevette tempura, avocat, salade, spicy',7.40,true,107),
  ('yakitoris','Yakitori Saumon','2 brochettes · saumon',5.60,true,108),
  ('yakitoris','Yakitori Bœuf Fromage','2 brochettes · bœuf, fromage',5.90,true,109),
  ('yakitoris','Yakitori Poulet Saté','2 brochettes · poulet, saté',5.00,true,110),
  ('yakitoris','Yakitori Thon','2 brochettes · thon',5.60,true,111),
  ('nouilles','Nouilles Mixte','nouilles sautées mixtes',13.50,true,112),
  ('nouilles','Nouilles au Bœuf','nouilles sautées au bœuf',13.00,true,113),
  ('nouilles','Nouilles au Poulet','nouilles sautées au poulet',12.50,true,114),
  ('nouilles','Nouilles aux Crevettes','nouilles sautées aux crevettes',13.50,true,115),
  ('nouilles','Nouilles Légumes','nouilles sautées aux légumes',11.50,true,116),
  ('entrees','Nems Crevettes ou Poulet x3','3 nems',4.80,true,117),
  ('entrees','Riz Nature',null,3.00,true,118),
  ('entrees','Riz Vinaigré',null,3.50,true,119),
  ('entrees','Gyozas Légumes x3','3 raviolis légumes',3.50,true,120),
  ('entrees','Gyozas Crevettes x3','3 raviolis crevettes',3.80,true,121),
  ('entrees','Crevettes Tempura x4','4 crevettes en beignet',6.00,true,122),
  ('entrees','Rouleaux de Printemps x2','2 rouleaux',6.00,true,123),
  ('entrees','Petite Salade Thaï Poulet ou Crevettes',null,7.50,true,124),
  ('entrees','Grande Salade Thaï Poulet ou Crevettes',null,9.50,true,125),
  ('entrees','Bobun Bœuf',null,12.00,true,126),
  ('entrees','Soupe Miso',null,3.00,true,127),
  ('entrees','Soupe Miso Saumon',null,4.00,true,128),
  ('entrees','Salade de Choux',null,3.00,true,129),
  ('entrees','Salade de Choux Saumon ou Crevettes',null,4.20,true,130),
  ('entrees','Salade Wakamé',null,5.30,true,131),
  ('menus','1. Menu Sushi Saumon','10 sushis saumon',19.00,true,132),
  ('menus','2. Menu Sushi Saumon & Thon','5 sushis saumon, 5 sushis thon',19.50,true,133),
  ('menus','3. Menu California','6 saumon avocat, 6 thon cuit avocat mayo, 6 concombre avocat cheese',17.50,true,134),
  ('menus','4. Menu Maki','6 thon cru/cuit, 6 saumon, 6 concombre',16.20,true,135),
  ('menus','5. Menu Crispy','6 saumon avocat, 6 thon cuit avocat mayo, 6 concombre avocat cheese',19.50,true,136),
  ('menus','6. Menu Salmon','6 avocat, 6 cheese, 6 boursin',18.50,true,137),
  ('menus','7. Menu Maki de Luxe','6 salmon avocat cheese, 6 maki light saumon avocat, 6 snow roll saumon cheese',18.00,true,138),
  ('menus','8. Menu Fuji','6 crispy saumon avocat boursin, 6 salmon cheese, 6 california saumon avocat',18.50,true,139),
  ('menus','9. Menu Kaito','6 california saumon avocat, 6 makis thon, 2 sushis saumon, 2 sushis thon',19.00,true,140),
  ('menus','10. Menu Chiba','6 california poulet mayo avocat, 6 maki light crevettes tempura, 6 california saumon avocat',19.00,true,141),
  ('menus','11. Menu Tokyo','6 salmon cheese, 6 salmon avocat cheese, 2 sushis saumon',17.50,true,142),
  ('menus','12. Menu Pink','6 salmon avocat cheese, 6 sashimis saumon, 4 sushis saumon',19.00,true,143),
  ('menus','13. Menu Nagoya','6 california saumon avocat, 6 maki saumon, 4 sushis saumon, 3 nems',22.00,true,144),
  ('menus','14. Menu Brochettes','1 paire fromage gouda, 1 paire poulet, 1 brochette saumon, riz nature',16.60,true,145),
  ('menus','15. Menu Mixte','1 paire bœuf gouda, 1 paire poulet, 2 sushis saumon, 6 california saumon',19.90,true,146),
  ('menus','16. Menu Kioto','6 california saumon avocat, 3 sashimis saumon, 3 sashimis thon, 2 sushis saumon, 2 sushis thon',19.20,true,147),
  ('menus-partager','Menu Two','Pour 2 · sushis, makis, california, salmon, maki light, 8 dragons + 2 accompagnements, 6 sauces',38.00,true,148),
  ('menus-partager','Menu Famille','Sushis, makis, california, salmon, snow roll, 8 dragons, 8 spécials + 3 accompagnements, 8 sauces',59.00,true,149),
  ('menus-partager','Menu Smile','Grand assortiment sushis, makis, california, crispy, salmon, maki light, 8 dragons, 8 rainbow + 5 accompagnements, 12 sauces',89.00,true,150),
  ('menus-partager','Big Smile','Très grand assortiment · sushis, sashimis, california, crispy, salmon, maki light, makis, snow roll, 8 dragons, 8 rainbow + 7 accompagnements, 15 sauces',139.00,true,151),
  ('desserts','Perle de Coco','3 pièces',4.20,true,152),
  ('desserts','Maki Nutella',null,5.00,true,153),
  ('desserts','Maki Nutella Banane',null,5.50,true,154),
  ('desserts','Salade Litchi',null,2.90,true,155),
  ('desserts','Salade de Fruits',null,3.90,true,156),
  ('desserts','Mochi','parfums variés',5.00,true,157),
  ('boissons','Canette 33cl',null,2.00,true,158),
  ('boissons','Bouteille',null,3.50,true,159)
) as v(cat_slug, name, description, price, is_available, display_order)
join categories c on c.slug = v.cat_slug
where not exists (select 1 from products p where p.name = v.name);
